// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZYkuSy0TU-5NYthX6RTL_XyCJlWn6oI',
    appId: '1:1022252630221:web:20f94ad84ca7eb18b6e984',
    messagingSenderId: '1022252630221',
    projectId: 'oh-app---dev',
    authDomain: 'oh-app---dev.firebaseapp.com',
    storageBucket: 'oh-app---dev.appspot.com',
    measurementId: 'G-9HK00QW624',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLrUgnPTRk36Gwq9V2RlDJEyhUO5fwO8',
    appId: '1:1022252630221:android:c195d9de6bc5d4cfb6e984',
    messagingSenderId: '1022252630221',
    projectId: 'oh-app---dev',
    storageBucket: 'oh-app---dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZRjiSkGZQG3bi3Wf266XC3ZF89bEuRi0',
    appId: '1:1022252630221:ios:193b67db44c1bd7db6e984',
    messagingSenderId: '1022252630221',
    projectId: 'oh-app---dev',
    storageBucket: 'oh-app---dev.appspot.com',
    androidClientId: '1022252630221-250bpeon1s3peogap6b58tv3fpva2l1u.apps.googleusercontent.com',
    iosClientId: '1022252630221-u0glfo34g8ukjbvr215imb3iu91dp9e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZRjiSkGZQG3bi3Wf266XC3ZF89bEuRi0',
    appId: '1:1022252630221:ios:193b67db44c1bd7db6e984',
    messagingSenderId: '1022252630221',
    projectId: 'oh-app---dev',
    storageBucket: 'oh-app---dev.appspot.com',
    androidClientId: '1022252630221-250bpeon1s3peogap6b58tv3fpva2l1u.apps.googleusercontent.com',
    iosClientId: '1022252630221-u0glfo34g8ukjbvr215imb3iu91dp9e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuJBgnRqX5vMUJ4tEjEG9WhTkLMeb_AjY',
    appId: '1:1022252630221:web:58dca1be4fd75b28b6e984',
    messagingSenderId: '1022252630221',
    projectId: 'oh-app---dev',
    authDomain: 'oh-app---dev.firebaseapp.com',
    storageBucket: 'oh-app---dev.appspot.com',
    measurementId: 'G-EBS54Y0LX6',
  );

}