// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS Firebase configuration not updated for new project.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS Firebase configuration not updated for new project.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_a7lPHqJBRI2TzxTIMiSPj-E7Xyqizs',
    appId: '1:272363630855:web:2af7d97ee450efb1d915a2',
    messagingSenderId: '272363630855',
    projectId: 'oh-app-bcf24',
    authDomain: 'oh-app-bcf24.firebaseapp.com',
    storageBucket: 'oh-app-bcf24.appspot.com',
    measurementId: 'G-DXDDZKBEJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk_a7lPHqJBRI2TzxTIMiSPj-E7Xyqizs',
    appId: '1:272363630855:android:f6b6d2dd60366d08d915a2',
    messagingSenderId: '272363630855',
    projectId: 'oh-app-bcf24',
    storageBucket: 'oh-app-bcf24.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk_a7lPHqJBRI2TzxTIMiSPj-E7Xyqizs',
    appId: '1:272363630855:web:2af7d97ee450efb1d915a2',
    messagingSenderId: '272363630855',
    projectId: 'oh-app-bcf24',
    authDomain: 'oh-app-bcf24.firebaseapp.com',
    storageBucket: 'oh-app-bcf24.appspot.com',
    measurementId: 'G-DXDDZKBEJD',
  );

}